ci: Fix west update pip requirements workflow
* The script would have been called from the PR which is insecure.
  Moving the script directly in the workflow.
* Hard code west install instead of using requirements-base.txt
* Running `west update zephyr` requires credentials, because the
  sdk-zephyr-next repo is private
* Drop the absolute paths used by the compile-requirements script
* The pip-requirements.txt file format changed, fixes the parsing
  of the packages in the compliance workflow

New output will look like this

```
 # pip-compile --allow-unsafe --annotation-style=line
   --output-file=nrf/scripts/requirements-fixed.txt --strip-extras
   bootloader/mcuboot/scripts/requirements.txt
   nrf/scripts/requirements-ci.txt nrf/scripts/requirements-extra.txt
   nrf/scripts/requirements.txt zephyr/scripts/requirements.txt
```

Signed-off-by: Sebastian Wezel <sebastian.wezel@nordicsemi.no>

diff --git a/.github/workflows/pip-requirements.yml b/.github/workflows/pip-requirements.yml
--- a/.github/workflows/pip-requirements.yml
+++ b/.github/workflows/pip-requirements.yml
@@ -44,13 +44,20 @@ jobs:
       - name: Setup environment
         working-directory: ncs
         run: |
-          pip3 install --user -U setuptools wheel pip virtualenv virtualenvwrapper
-          pip3 install -r nrf/scripts/requirements-base.txt
+          pip3 install --user -U setuptools wheel pip virtualenv virtualenvwrapper west
+          # The credential setup was copied from the compliance workflow
+          git config --global user.email "pylon@nordicsemi.no"
+          git config --global user.name "Nordic Builder"
+          # enable the local store credential helper
+          git config --global credential.helper store
+          # add credential
+          echo "https://x-access-token:${{ secrets.NCS_GITHUB_TOKEN }}@github.com" >> ~/.git-credentials
           west init -l nrf
           west update --narrow mcuboot zephyr
+          rm ~/.git-credentials
 
       - name: Execute script diff action
-        uses: nordicbuilder/action-script-diff@main
+        uses: nordicbuilder/action-script-diff@v0.1
         with:
           github-token: ${{ secrets.NCS_GITHUB_TOKEN }}
           message_diff: |
@@ -68,10 +75,42 @@ jobs:
           message_success: |
             The changes to the 'requirements-fixed.txt' have been added to this PR.
             All further changes to any of the requirements file will automatically be applied as long an :$REACT_EMOTE: is present.
-          script_call: scripts/compile-requirements.sh scripts/requirements-fixed.txt
           git_diff_root: ncs/nrf
           diff_path: scripts
           diff_file: requirements-fixed.txt
           reaction_emote: "${{ env.REACT_EMOTE }}"
           git_user_name: "Nordic Builder"
           git_user_email: "pylon@nordicsemi.no"
+          script_call: |
+            OUT_FILE="nrf/scripts/requirements-fixed.txt"
+            echo "Writing frozen requirements to: $OUT_FILE"
+            echo "Log python version: $(python --version)"
+
+            TOPDIR=$(west topdir)
+            cd $TOPDIR
+
+            source ~/.local/bin/virtualenvwrapper.sh
+            [[ $? != 0 ]] && echo "error sourcing virtualenvwrapper" && exit 1
+
+            rmvirtualenv pip-fixed-venv > /dev/null 2>&1
+            # We need to force the result of the following command.
+            # For no aparent reason it returns 1 with the same output as local.
+            mkvirtualenv pip-fixed-venv  > /dev/null 2>&1 || true
+            workon pip-fixed-venv  > /dev/null 2>&1
+            pip3 install pip-tools > /dev/null 2>&1
+            pip3 install setuptools --upgrade
+
+            pip-compile \
+                --build-isolation \
+                --strip-extras \
+                --annotation-style line \
+                --allow-unsafe \
+                --output-file $OUT_FILE \
+                bootloader/mcuboot/scripts/requirements.txt \
+                zephyr/scripts/requirements.txt  \
+                nrf/scripts/requirements.txt \
+                nrf/scripts/requirements-ci.txt \
+                nrf/scripts/requirements-extra.txt
+
+            deactivate
+            rmvirtualenv pip-fixed-venv
